### ISSUE TITLE
You made a typo in "variables-and-initializing-in-c.md".

### ISSUE THREAD

**Issue by kssim** [Dry8r3aD/TodayILearned#1]
You made a typo in "variables-and-initializing-in-c.md".

In content.
"What I knew untill now about vriable initalization"

vriable is typo.
vriable => variable.

**Comment by Dry8r3aD** [comment]
thank you for letting me know :) 
i'll fix this right away

**Comment by kssim** [comment]
You're welcome.
I saw the special message you have left.
Thanks :)
